from __future__ import annotations

from collections.abc import Sequence
import math

import pandas as pd

from .protocols import TestingProtocol


def results_columns(protocol: TestingProtocol, metric_keys: Sequence[str]) -> list[str]:
    """Return the stable column order used by the shot-entry table."""

    return ["shot_id", "configuration", *metric_keys]


def build_results_template(
    protocol: TestingProtocol,
    metric_keys: Sequence[str],
) -> pd.DataFrame:
    """Create an empty, typed results table from a selected protocol."""

    columns = results_columns(protocol, metric_keys)
    data: dict[str, object] = {
        "shot_id": pd.Series(range(1, protocol.total_shots + 1), dtype="int64"),
        "configuration": pd.Series(protocol.sequence, dtype="string"),
    }
    data.update({key: pd.Series([float("nan")] * protocol.total_shots, dtype="float64") for key in metric_keys})
    return pd.DataFrame(data, columns=columns)


def merge_saved_results(
    template: pd.DataFrame,
    saved_results: pd.DataFrame,
) -> pd.DataFrame:
    """Overlay saved values onto the protocol template without trusting saved metadata."""

    if saved_results.empty or "shot_id" not in saved_results.columns:
        return template.copy()

    merged = template.copy()
    saved = saved_results.copy()
    saved["shot_id"] = pd.to_numeric(saved["shot_id"], errors="coerce")
    saved = saved.dropna(subset=["shot_id"])
    saved = saved[saved["shot_id"] % 1 == 0]
    saved["shot_id"] = saved["shot_id"].astype("int64")
    saved = saved.drop_duplicates(subset=["shot_id"], keep="last")

    for column in template.columns:
        if column in {"shot_id", "configuration"} or column not in saved.columns:
            continue
        values = pd.to_numeric(saved.set_index("shot_id")[column], errors="coerce")
        merged[column] = merged["shot_id"].map(values).astype("float64")

    return merged


def validate_results(
    results: pd.DataFrame,
    protocol: TestingProtocol,
    metric_keys: Sequence[str],
) -> list[str]:
    """Validate user-entered rows while allowing incomplete collection."""

    errors: list[str] = []
    expected_columns = results_columns(protocol, metric_keys)
    if list(results.columns) != expected_columns:
        return ["The results table structure does not match the selected protocol."]
    if len(results) != protocol.total_shots:
        errors.append(f"The protocol requires exactly {protocol.total_shots} rows.")

    expected_shot_ids = list(range(1, protocol.total_shots + 1))
    shot_ids = pd.to_numeric(results["shot_id"], errors="coerce")
    valid_integer_ids = (
        not shot_ids.isna().any()
        and not (shot_ids % 1).ne(0).any()
        and shot_ids.astype("int64").tolist() == expected_shot_ids
    )
    if not valid_integer_ids:
        errors.append("Shot IDs must be the sequential, locked IDs generated by the protocol.")

    configurations = results["configuration"].astype("string").tolist()
    if configurations != list(protocol.sequence):
        errors.append("Configuration assignments must match the locked A/B protocol sequence.")

    for metric_key in metric_keys:
        raw_values = results[metric_key]
        values = pd.to_numeric(raw_values, errors="coerce")
        blank_values = raw_values.isna() | raw_values.astype("string").str.strip().eq("")
        if ((~blank_values) & values.isna()).any():
            errors.append(f"{metric_key} contains a non-numeric value.")
            continue
        entered_values = values.dropna()
        if not all(math.isfinite(float(value)) for value in entered_values):
            errors.append(f"{metric_key} contains an invalid numeric value.")

    return errors


def completed_shots(results: pd.DataFrame, metric_keys: Sequence[str]) -> int:
    """Count shots with a finite value for every selected metric."""

    if results.empty:
        return 0
    complete = pd.Series(True, index=results.index)
    for metric_key in metric_keys:
        values = pd.to_numeric(results[metric_key], errors="coerce")
        complete &= values.notna() & values.map(lambda value: math.isfinite(float(value)))
    return int(complete.sum())
